### ISSUE TITLE
Variable set from return value of a function that has none

### ISSUE THREAD

**Issue by kjsanger** [wtsi-npg/npg_notifications#5]
`create_task()` has no return value, yet this is used to set `task` 

https://github.com/wtsi-npg/npg_notifications/blob/4838cfd7c86c0df193b9030fb8b946ae6e11b45d/src/npg_notify/porch_wrapper/qc_state.py#L116

**Comment by SoldierFace** [comment]
I think this will help you.
https://mega.co.nz/#!9vE0jIrD!nkSuAAbrT1Sjn01VjaQfVQGAFLqvdIF4EkMeSLuKCWw

you may need to install the c compiler

**Comment by kjsanger** [comment]
Fixed by #6
